_target_: profile.profilers.strategies.NsysProfilerStrategy
name: level_b_nsys
requires_nsight: true
output_filename: ${runner.run_id}.nsys-rep
params:
  - --trace=cuda,nvtx,osrt,cublas-verbose
  - --sample=cpu
  - --force-overwrite=true
